input_dir: "/proj/omics/env-bio/2025/collaboration/hochroth_negroni_finalproj/data/med_genomes/size20_180/"
input_data: "/proj/omics/env-bio/2025/collaboration/hochroth_negroni_finalproj/data/"

input_folder:
 # --- MEDITERRANEA SEQUENCES ---
 # --- surface 0.8-5
 #   - "ERR538173"
 #   - "ERR538186"
 #   - "ERR868356"
 #   - "ERR868369"
 #   - "ERR868389"
 #   - "ERR868393"
 #   - "ERR868397"
 #   - "ERR868401"
 #   - "ERR868402"
 #   - "ERR868403"
 #   - "ERR868406"
 #   - "ERR868407"
 #   - "ERR868408"
 #   - "ERR868412"
 #   - "ERR868428"
 #   - "ERR868431"
 #   - "ERR868456"
 #   - "ERR868460"
 #   - "ERR868471"
 #   - "ERR868497"
 #   - "ERR868498"
 #   - "ERR868503"
 #   - "ERR868504"
# --- surface W5_20
#    - "ERR1700895"
#    - "ERR1700896"
#    - "ERR1700899" 
#    - "ERR1726540"
#    - "ERR1726542"
#    - "ERR1726555"
#    - "ERR1726722"
#    - "ERR1726929"
#    - "ERR538178"
#    - "ERR538184"
#    - "ERR538190"
# --- surface 20-180 ---
     - "ERR1700914"
     - "ERR1726587"
     - "ERR1726642"
     - "ERR1726673"
     - "ERR1726751"
     - "ERR1726791"
     - "ERR1726870"
     - "ERR1726918"
     - "ERR1726951"
     - "ERR1726976"
     - "ERR538171"
     - "ERR538189"
     - "ERR1726546"
     - "ERR1726613"
     - "ERR1726660"
     - "ERR1726675"
     - "ERR1726777"
     - "ERR1726838"
     - "ERR1726902"
     - "ERR1726942"
     - "ERR1726956"
     - "ERR1726979"
     - "ERR538183"


 #   --- PACIFIC SEQUENCES
    #- "ERR1726688"
    #- "ERR1726938"
    #- "ERR1726522"
    #- "ERR1726961"
    #- "ERR1726533"
    #- "ERR1726571"
